require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'
rn_maps_path = '../node_modules/react-native-maps'
rna_kako_sdk_path = '../node_modules/@actbase/react-native-kakaosdk/ARNKakaoSDK.podspec'

platform :ios, '11.0'

target 'zipanda' do
  pod 'ARNKakaoSDK', :path =>rna_kako_sdk_path
  pod 'react-native-google-maps', :path => rn_maps_path

  config = use_native_modules!
  
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  use_react_native!(:path => config["reactNativePath"])
 
  #pod 'ARNKakaoLink', :path => '../node_modules/@actbase/react-native-kakao-link'

  target 'zipandaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  
  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  use_flipper!({  'Flipper' => '0.86.0'})
  post_install do |installer|
    flipper_post_install(installer)
  end
  
end

target 'zipanda-tvOS' do
  # Pods for zipanda-tvOS

  target 'zipanda-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
